### ISSUE TITLE
Won't run on node v6.2.2, npm 3.9.5

### ISSUE THREAD

**Issue by wolfjuli** [jsanchesleao/futuristic#1]
The folder structure seems not valid. 

Reproduce:

```
  npm init
  npm install --save fantasy-future
  echo "var test = require('fantasy-future');" > index.js
  node index.js 
  module.js:442
    throw err;
    ^

  Error: Cannot find module 'fantasy-future'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/tmp/asdf/index.js:1:74)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

```

**Comment by wolfjuli** [comment]
we think it is not useable as nodejs module because you use ES6 export syntax.
